version: '3.8'

services:
  wst-flyway:
    build: .
    image: wst-flyway:latest
    environment:
      - FLYWAY_URL=jdbc:postgresql://${FLYWAY_PGSQL_HOST}:${FLYWAY_PGSQL_PORT}/${FLYWAY_PGSQL_DATABASE}
      - FLYWAY_USER=${FLYWAY_PGSQL_USERNAME}
      - FLYWAY_PASSWORD=${FLYWAY_PGSQL_PASSWORD}
      - FLYWAY_LOCATIONS=filesystem:/flyway/sql
    networks:
      - db-network
    command: info

  # Example commands:
  # docker-compose run --rm wst-flyway migrate
  # docker-compose run --rm wst-flyway info
  # docker-compose run --rm wst-flyway validate

networks:
  db-network:
    driver: bridge