# Example ConfigMap for Flyway configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: wst-flyway-config
data:
  FLYWAY_PGSQL_HOST: "postgres-service"
  FLYWAY_PGSQL_PORT: "5432"
  FLYWAY_PGSQL_DATABASE: "postgres"
---
# Example Secret for database credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  FLYWAY_PGSQL_USERNAME: myuser
  FLYWAY_PGSQL_PASSWORD: mypassword
---
# Example Kubernetes Job for running Flyway migrations
apiVersion: batch/v1
kind: Job
metadata:
  name: wst-flyway-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wst-flyway
        image: ghcr.io/wst-flyway:dev
        command: ["flyway", "migrate"]
        envFrom:
        - configMapRef:
            name: wst-flyway-config
        - secretRef:
            name: postgres-credentials
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://$(FLYWAY_PGSQL_HOST):$(FLYWAY_PGSQL_PORT)/$(FLYWAY_PGSQL_DATABASE)"
        - name: FLYWAY_USER
          value: "$(FLYWAY_PGSQL_USERNAME)"
        - name: FLYWAY_PASSWORD
          value: "$(FLYWAY_PGSQL_PASSWORD)"
        - name: FLYWAY_LOCATIONS
          value: "filesystem:/flyway/sql"