# tbls configuration for ATP schema documentation
dsn: postgres://postgres:postgres@localhost:5432/test_db?sslmode=disable
docPath: docs/
er:
  skip: false
  format: svg
  comment: true
  distance: 1
format:
  normalize: true
  adjust: true
  hideColumnsWithoutValues: false
  hideNoDescriptionTableComment: false
  hideNoDescriptionColumnComment: false
  hideAdditionalComments: false
  includeMatviews: true
  includeViews: true
  includeSequences: true
  includeTriggers: true
  includeConstraints: true
  includeIndexes: true
  includeFunctions: true
  includeProcedures: true
  includeTypes: true
  includeRoles: true
  includeGrants: true
exclude:
  - information_schema
  - performance_schema
  - sys
  - mysql
  - pg_catalog
  - pg_toast
  - pg_temp_1
  - pg_toast_temp_1
include:
  - atp
markdown:
  number: true
  toc: true
  erFormat: svg
  badge: true
  excludeType: false