name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - stg
      - dev
  pull_request:
    branches:
      - stg
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/wst-flyway

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Branch name (e.g., dev, main)
            type=ref,event=branch
            # PR number (e.g., pr-123)
            type=ref,event=pr
            # 8-character SHA only
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-migrations:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name != 'pull_request'
    
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test migrations with Flyway
        run: |
          docker run --rm \
            --network ${{ job.services.postgres.network }} \
            -e FLYWAY_URL="jdbc:postgresql://postgres:5432/test_db" \
            -e FLYWAY_USER="postgres" \
            -e FLYWAY_PASSWORD="postgres" \
            -e FLYWAY_LOCATIONS="filesystem:/flyway/sql" \
            -v "${{ github.workspace }}/migrations:/flyway/sql:ro" \
            flyway/flyway:11.10.0-alpine \
            migrate

      - name: Validate migrations
        run: |
          docker run --rm \
            --network ${{ job.services.postgres.network }} \
            -e FLYWAY_URL="jdbc:postgresql://postgres:5432/test_db" \
            -e FLYWAY_USER="postgres" \
            -e FLYWAY_PASSWORD="postgres" \
            -e FLYWAY_LOCATIONS="filesystem:/flyway/sql" \
            -v "${{ github.workspace }}/migrations:/flyway/sql:ro" \
            flyway/flyway:11.10.0-alpine \
            validate